name: Flare
options:
  bundleIdPrefix: com.flare
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    ALWAYS_SEARCH_USER_PATHS: false

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    from: "9.1.0"

targetTemplates:
  FlareApp:
    type: application
    sources:
      - path: Noiseless
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flare.app
        INFOPLIST_FILE: Noiseless/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Flare
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
    dependencies:
      - package: Supabase
        product: Supabase
      - package: FeedKit
    entitlements:
      path: Noiseless/Resources/Noiseless.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true

targets:
  Flare-iOS:
    templates:
      - FlareApp
    platform: iOS
    settings:
      base:
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"

  Flare-macOS:
    templates:
      - FlareApp
    platform: macOS
    settings:
      base:
        SDKROOT: macosx
        SUPPORTED_PLATFORMS: macosx
